import type { WeightFluidEntry } from "./fluid.types";

/* Demo entries, so the table and the recent list are not blank on a first
   visit. Deletable in one commit when real accounts arrive. */

export const SEED_ENTRIES: WeightFluidEntry[] = [
  {
    id: "1",
    dateEn: "May 10, 2024",
    dateEs: "10 May, 2024",
    morning: "100",
    evening: "182",
    uo: "High",
    intake: "50",
    goal: "Above Goal",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Above EDW",
    fluidStatusMsg: "Possible Fluid Overload",
    notes: "--",
    noteKey: null,
  },
  {
    id: "2",
    dateEn: "May 31, 2024",
    dateEs: "31 May, 2024",
    morning: "123",
    evening: "122",
    uo: "High",
    intake: "40",
    goal: "Goal Met",
    swelling: "Mild",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Near EDW",
    fluidStatusMsg: "Appears On Target",
    notes: "Felt good today",
    noteKey: "feltGood",
  },
  {
    id: "3",
    dateEn: "June 7, 2024",
    dateEs: "7 Jun, 2024",
    morning: "95",
    evening: "150",
    uo: "High",
    intake: "45",
    goal: "Above Goal",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Above EDW",
    fluidStatusMsg: "Possible Fluid Overload",
    notes: "Need to push harder",
    noteKey: "needToPush",
  },
  {
    id: "4",
    dateEn: "June 14, 2024",
    dateEs: "14 Jun, 2024",
    morning: "110",
    evening: "170",
    uo: "High",
    intake: "55",
    goal: "Goal Met",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Above EDW",
    fluidStatusMsg: "Possible Fluid Overload",
    notes: "Strong finish",
    noteKey: "strongFinish",
  },
  {
    id: "5",
    dateEn: "June 21, 2024",
    dateEs: "21 Jun, 2024",
    morning: "118",
    evening: "190",
    uo: "High",
    intake: "60",
    goal: "Above Goal",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Above EDW",
    fluidStatusMsg: "Possible Fluid Overload",
    notes: "Best performance yet",
    noteKey: "bestPerformance",
  },
  {
    id: "6",
    dateEn: "June 28, 2024",
    dateEs: "28 Jun, 2024",
    morning: "102",
    evening: "120",
    uo: "High",
    intake: "35",
    goal: "Goal Met",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Below EDW",
    fluidStatusMsg: "Possible Too Much Fluid Removed",
    notes: "Felt tired",
    noteKey: "feltTired",
  },
  {
    id: "7",
    dateEn: "July 5, 2024",
    dateEs: "5 Jul, 2024",
    morning: "115",
    evening: "165",
    uo: "High",
    intake: "50",
    goal: "Above Goal",
    swelling: "None",
    sob: "NO",
    weakness: "NO",
    rapidGain: "NO",
    dizziness: "NO",
    cramping: "NO",
    nausea: "NO",
    fluidStatus: "Above EDW",
    fluidStatusMsg: "Possible Fluid Overload",
    notes: "--",
    noteKey: null,
  },
];
