import { Apple, Bone, Droplet, FlaskConical, HeartPulse } from "lucide-react";
import { Kidneys } from "@/components/icons/Kidneys";
import type { CategoryGroup } from "./labs.panel.types";

/* The reference panels and their demo readings. Deletable in one commit
   when real results arrive from the lab. */

export const LAB_CATEGORIES: CategoryGroup[] = [
  {
    id: "kidney-function",
    name: "KIDNEY FUNCTION",
    icon: Kidneys,
    tests: [
      {
        id: "bun",
        name: "BUN",
        latestResult: "48 mg/dL",
        previousResult: "46 mg/dL",
        change: "2",
        changeDirection: "up",
        changeColor: "red",
        refRange: "7 – 20 mg/dL",
        status: "High",
        sparkline: [35, 38, 42, 46, 48],
      },
      {
        id: "creatinine",
        name: "Creatinine",
        latestResult: "6.48 mg/dL",
        previousResult: "6.12 mg/dL",
        change: "0.36",
        changeDirection: "up",
        changeColor: "red",
        refRange: "0.6 – 1.3 mg/dL",
        status: "High",
        sparkline: [5.2, 5.5, 5.8, 6.12, 6.48],
      },
      {
        id: "egfr",
        name: "eGFR (CKD-EPI)",
        latestResult: "9 mL/min/1.73m²",
        previousResult: "10 mL/min/1.73m²",
        change: "1",
        changeDirection: "down",
        changeColor: "red",
        refRange: "> 90 mL/min/1.73m²",
        status: "Low",
        sparkline: [12, 11, 11, 10, 9],
      },
    ],
  },
  {
    id: "electrolytes",
    name: "ELECTROLYTES",
    icon: FlaskConical,
    tests: [
      {
        id: "sodium",
        name: "Sodium",
        latestResult: "138 mEq/L",
        previousResult: "137 mEq/L",
        change: "1",
        changeDirection: "up",
        changeColor: "green",
        refRange: "135 – 145 mEq/L",
        status: "In Range",
        sparkline: [136, 136, 137, 137, 138],
      },
      {
        id: "potassium",
        name: "Potassium",
        latestResult: "5.2 mEq/L",
        previousResult: "5.0 mEq/L",
        change: "0.2",
        changeDirection: "up",
        changeColor: "orange",
        refRange: "3.5 – 5.0 mEq/L",
        status: "High",
        sparkline: [4.6, 4.8, 4.9, 5.0, 5.2],
      },
      {
        id: "chloride",
        name: "Chloride",
        latestResult: "99 mEq/L",
        previousResult: "101 mEq/L",
        change: "2",
        changeDirection: "down",
        changeColor: "green",
        refRange: "98 – 107 mEq/L",
        status: "In Range",
        sparkline: [102, 101, 100, 101, 99],
      },
      {
        id: "co2",
        name: "CO2 (Bicarbonate)",
        latestResult: "22 mEq/L",
        previousResult: "23 mEq/L",
        change: "1",
        changeDirection: "down",
        changeColor: "green",
        refRange: "22 – 29 mEq/L",
        status: "In Range",
        sparkline: [24, 23, 23, 23, 22],
      },
    ],
  },
  {
    id: "mineral-bone",
    name: "MINERAL & BONE",
    icon: Bone,
    tests: [
      {
        id: "calcium",
        name: "Calcium",
        latestResult: "9.1 mg/dL",
        previousResult: "9.3 mg/dL",
        change: "0.2",
        changeDirection: "down",
        changeColor: "green",
        refRange: "8.5 – 10.5 mg/dL",
        status: "In Range",
        sparkline: [9.4, 9.3, 9.2, 9.3, 9.1],
      },
      {
        id: "phosphorus",
        name: "Phosphorus",
        latestResult: "5.6 mg/dL",
        previousResult: "5.3 mg/dL",
        change: "0.3",
        changeDirection: "up",
        changeColor: "red",
        refRange: "2.5 – 4.5 mg/dL",
        status: "High",
        sparkline: [4.8, 5.0, 5.1, 5.3, 5.6],
      },
      {
        id: "pth",
        name: "PTH (Intact)",
        latestResult: "412 pg/mL",
        previousResult: "386 pg/mL",
        change: "26",
        changeDirection: "up",
        changeColor: "red",
        refRange: "15 – 65 pg/mL",
        status: "High",
        sparkline: [340, 360, 375, 386, 412],
      },
      {
        id: "vitamind",
        name: "Vitamin D 25-OH",
        latestResult: "28 ng/mL",
        previousResult: "27 ng/mL",
        change: "1",
        changeDirection: "up",
        changeColor: "orange",
        refRange: "30 – 100 ng/mL",
        status: "Low",
        sparkline: [24, 25, 26, 27, 28],
      },
    ],
  },
  {
    id: "blood-counts",
    name: "BLOOD COUNTS",
    icon: Droplet,
    tests: [
      {
        id: "hemoglobin",
        name: "Hemoglobin",
        latestResult: "10.2 g/dL",
        previousResult: "10.0 g/dL",
        change: "0.2",
        changeDirection: "up",
        changeColor: "orange",
        refRange: "11.0 – 16.0 g/dL",
        status: "Low",
        sparkline: [9.5, 9.7, 9.8, 10.0, 10.2],
      },
      {
        id: "hematocrit",
        name: "Hematocrit",
        latestResult: "31 %",
        previousResult: "30 %",
        change: "1",
        changeDirection: "up",
        changeColor: "orange",
        refRange: "33 – 47 %",
        status: "Low",
        sparkline: [28, 29, 29, 30, 31],
      },
      {
        id: "ferritin",
        name: "Ferritin",
        latestResult: "456 ng/mL",
        previousResult: "438 ng/mL",
        change: "18",
        changeDirection: "up",
        changeColor: "red",
        refRange: "30 – 400 ng/mL",
        status: "High",
        sparkline: [410, 420, 430, 438, 456],
      },
      {
        id: "tsat",
        name: "Iron Saturation (TSAT)",
        latestResult: "28 %",
        previousResult: "26 %",
        change: "2",
        changeDirection: "up",
        changeColor: "green",
        refRange: "20 – 50 %",
        status: "In Range",
        sparkline: [23, 24, 25, 26, 28],
      },
    ],
  },
  {
    id: "nutrition",
    name: "NUTRITION",
    icon: Apple,
    tests: [
      {
        id: "albumin",
        name: "Albumin",
        latestResult: "3.8 g/dL",
        previousResult: "3.7 g/dL",
        change: "0.1",
        changeDirection: "up",
        changeColor: "green",
        refRange: "3.5 – 5.0 g/dL",
        status: "In Range",
        sparkline: [3.5, 3.6, 3.6, 3.7, 3.8],
      },
      {
        id: "bicarbonate",
        name: "Bicarbonate",
        latestResult: "22 mEq/L",
        previousResult: "23 mEq/L",
        change: "1",
        changeDirection: "down",
        changeColor: "green",
        refRange: "22 – 29 mEq/L",
        status: "In Range",
        sparkline: [24, 23, 23, 23, 22],
      },
    ],
  },
  {
    id: "dialysis-adequacy",
    name: "DIALYSIS ADEQUACY",
    icon: HeartPulse,
    tests: [
      {
        id: "ktv",
        name: "Kt/V",
        latestResult: "1.35",
        previousResult: "1.30",
        change: "0.05",
        changeDirection: "up",
        changeColor: "green",
        refRange: "≥ 1.20",
        status: "In Range",
        sparkline: [1.22, 1.25, 1.28, 1.3, 1.35],
      },
    ],
  },
];
